In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import numpy as np
a=np.array([12.3,121])
print(a)
print(type(a))

[ 12.3 121. ]
<class 'numpy.ndarray'>


In [29]:
#import numpy as np (as per call her libraries)
#conversion of type code
arr=np.array([1,2,3,4],dtype='i8')
arr.dtype


dtype('int64')

In [25]:
arr=np.array([1,2,3,4],dtype='f8')
arr.dtype

dtype('float64')

In [30]:
arr=np.array([1,2,3,4],dtype='g')
arr.dtype

dtype('float64')

In [ ]:
#f4 and  g is identical thats is float 64
#dtype coversion of datatypes





In [12]:
import time
size=100000
list1=range(size)
list2=range(size)
start = time.time()
result = [x+y for x,y in zip(list1,list2)]
end = time.time()
print("python list time:" ,end-start)

array1 = np.arange(size)
array2 = np.arange(size)
start= time.time()
result = array1 + array2
end = time.time()
print("python array time",end - start)

python list time: 0.010190963745117188
python array time 0.0012557506561279297


In [17]:
a = np.array([1,2,3,4,5])
a.ndim# to find the dimensional
a.dtype

dtype('int64')

In [27]:
#shape was defined by axis of the array rows and column (x-axis,y-axis)
a.shape
a.size
a.ndim #dimetionalit

5

In [1]:
#to give input in user and make a list
l=[]
for i in range(1,6):
    a=int(input("enter the number:"))
    l.append(a)

print(l)

enter the number: 55
enter the number: 55
enter the number: 55
enter the number: 55
enter the number: 78


[55, 55, 55, 55, 78]


In [2]:
print(type(l))

<class 'list'>


In [11]:
arr=np.array(l)
print(arr)
#print(type(arr))

[55 55 55 55 78]


In [12]:
#tp represent the dimension
arr.ndim

1

In [22]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [26]:
arr.shape


(2, 3)

In [25]:
arr.ndim

2

In [27]:
arr=np.array([1,2,3,4],dtype="float32")#tycode
arr.dtype

dtype('float32')

In [28]:
arr=np.array([1,2,3,4],dtype="complex64")#tycode to covery array in complex value
arr.dtype

dtype('complex64')

In [29]:
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [33]:
# to create a diagonal metrix
arr= np.eye(3,k=-1)#eye work on parameter
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [31]:
# identity doesn't work on parameter
arr= np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
arr= np.eye(3,5,k=1)#eye work on parameter
print(arr)





[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


pip install matplotlib

In [8]:
import numpy as np

In [13]:
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [ ]:
array([1,2,3,4,5])


In [17]:
arr[0] = 30   #changing the element of an array

In [16]:
arr

array([1, 2, 3, 4, 5])

In [19]:
print(arr[1:4])

[2 3 4]


In [22]:
print(arr[-1:-3:-1])


[5 4]


In [24]:
print(arr[-1:-6:-2])

[ 5  3 30]


In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a = arr[arr>5]
#print(arr[arr<5])

In [34]:
a.ndim
a


array([6, 7, 8, 9])

In [36]:
arr[2]

array([7, 8, 9])

In [43]:
l=[]
for i in range(1,6):
    a=int(input("enter the number:"))
    if(a%2==0):
        l.append(a)
print(l)

enter the number: 2
enter the number: 5
enter the number: 4
enter the number: 8
enter the number: 7


[2, 4, 8]


In [44]:
l = [1,2,3,4,5,6,7,8]
l1 =[]
for i in l:
    if i%2==0:
        l1.append(i)
    else:
        continue
print(l1)

[2, 4, 6, 8]


In [45]:
arr = np.array(l1)

In [46]:
arr

array([2, 4, 6, 8])

In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
devisible_by2 = arr[arr%2==0]
print(devisible_by2)

[2 4 6 8]


In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
devisible_by3 = arr[arr%3==0]
print(devisible_by3)

[3 6 9]


In [55]:
arr = np.arange(0,10,3)
arr
arr = np.arange(0,10,2)
arr
arr = np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [58]:
arr = np.arange(0,10,3)
arr

array([0., 0., 0., 0., 0.])

In [74]:
arr = np.ones(5,dtype="f2")
arr

array([1., 1., 1., 1., 1.], dtype=float16)

In [70]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [68]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([7,8,9,10,11,12])


arr3 = np.concatenate((arr1,arr2))
arr3

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12])

In [75]:
arr = np.empty(5)
arr

array([0., 0., 0., 0., 0.])

In [77]:
arr[0]=10


In [78]:
arr

array([10.,  0.,  0.,  0.,  0.])

In [3]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd